consolations = [
    "Không sao, lần sau may mắn hơn!",
    "Hãy thử lại, bạn sẽ thành công!",
    "Cố lên, đừng nản lòng!",
    "Gãy Rồi Khóc Thôi :)))",
    "Cố lên nào đại gia, còn 1 xíu nữa là ăn rồi :’)",
    "Gần thắng rồi, kiên nhẫn nhé đại gia ❤️",
    "1 tay nữa là gỡ lại tất cả!",
    "Đừng nản lòng nhé, em tin đại gia mà :3",
    "All in tay cuối đi đại gia, biết đâu JackPot 🫣",
    "Đừng vì 1 trận thua mà nản lòng nhé chàng trai, ta tin cậu",
    "Sóng gió càng lớn, cơ hội chiến thắng càng cao. Đừng từ bỏ hy vọng!",
    "Thất bại là mẹ của thành công. Đại gia hãy thử lại và chiến thắng sẽ đến!",
    "May mắn không phải lúc nào cũng mỉm cười, nhưng đừng để nó bỏ rơi bạn lúc nào không hay.",
    "Quay một vòng nữa, biết đâu vận may sẽ mỉm cười với bạn!",
    "Hãy nhớ, mỗi lần thua là một bài học, và mỗi bài học đều mang lại giá trị riêng.",
    "Đôi khi may mắn chỉ là một quyết định dũng cảm. Hãy thử lại!",
    "Khi cánh cửa may mắn đóng lại, cửa sổ may mắn mở ra. Đừng bỏ lỡ cơ hội!",
    "Chỉ cần bạn không từ bỏ, thắng lợi cuối cùng vẫn còn trong tầm tay.",
    "May mắn sẽ đến với những ai kiên trì và không sợ thất bại. Cứ thế mà tiến lên!",
    "Hãy coi mỗi thất bại là một bước đệm để tiến gần hơn đến thành công. Còn nhiều cơ hội phía trước!",
    "Hãy giữ vững tinh thần, đừng để những thất bại tạm thời làm nản lòng bạn.",
    "Đại gia là người bản lĩnh, hãy vượt qua thử thách này và chứng minh bản thân!",
    "Còn nước còn tát, đừng vội bỏ cuộc. Hãy chiến đấu đến cùng!",
    "Vận may có thể đến bất chợt, hãy luôn sẵn sàng nắm bắt cơ hội!",
    "Niềm tin là chìa khóa dẫn đến thành công. Hãy tin tưởng vào bản thân và chiến thắng sẽ thuộc về bạn!",
    "Hãy luôn giữ cho mình một tâm lý thoải mái và tỉnh táo khi chơi. Đó là chìa khóa để chiến thắng.",
    "Hãy biến những lời nghi ngờ của người khác thành động lực để chiến thắng.",
    "Chiến thắng hay thất bại đều là một phần của cuộc chơi. Hãy học hỏi từ nó và tiếp tục tiến lên.",
    "Bình Tĩnh Còn Thắng Được",
    "Chỉ Cần Bạn Có Mặt Thắng Thua Không Quan Trọng",
    "Trong Cái Rủi Có Cái Xui",
    "Phát Sau Tất Tay, Được ăn cả hoặc ngả về không",
    "Đen Thôi Đỏ Quên Đi",
    "Thua Keo Này Ta Bày Keo Khác",
    "Thất Bại Là Mẹ Của Thành Công",
    "Em Đen Lắm",
    "Đừng Khóc Nhé Em",
    "Tự Tin Lên Bạn All Tài Là Win",
    "Ai Sợ Thì Đi Về All Xỉu Đi Em",
    "Muốn nhìn thấy cầu vồng, bạn phải biết chịu đựng cơn mưa",
    "Liều Thì Ăn Nhiều, Không Liều Thì Ăn Ít",
    "Nếu bạn lo sợ thất bại thì bạn không xứng đáng để thành công",
    "Đừng lo về thất bại; bạn chỉ cần đúng một lần thôi",
    "Bỏ cuộc chắc chắn là cách duy nhất để thất bại",
    "Tin Anh Phát Sau Cứ All Tài Là Húp",
    "Thôi Đi Cắm Sổ Đỏ Nạp Víp Mới Win Em Ạ",
    "Gãy Rồi Anh Long Ơi :))",
    "Khen Anh Duck Đẹp Trai Mới Win Được :))",
]
